- src/core/client/interfaces/Meta.ts
- src/core/client/interfaces/Player.ts
- src/core/client/startup.ts
- src/core/client/systems/meta.ts
- src/core/client/views/characters/characters.ts
- src/core/client/views/creator/creator.ts
- src/core/client/views/login/login.ts
- src/core/resource.cfg
- src/core/server/athena/index.ts
- src/core/server/database/index.ts
- src/core/server/events/playerConnect.ts
- src/core/server/interface/Player.ts
- src/core/server/views/characters.ts
- src/core/server/views/creator.ts
- src/core/server/views/login.ts
- src/core/shared/enums/meta.ts
- src/core/shared/enums/views.ts
* Refactors Event Names to use Enums
* Enums are shared on the server-side and client-side.
* Removes kick events for unrequested events. Just cancels their request.
> Refactor Event Names & Direction

- src/core/client/interfaces/Vehicle.ts
- src/core/client/startup.ts
- src/core/client/systems/vehicle.ts
- src/core/client/utility/marker.ts
- src/core/client/utility/text.ts
- src/core/server/interface/Player.ts
- src/core/shared/enums/events.ts
- src/core/shared/interfaces/Vector.ts
- src/core/shared/utility/vector.ts
This is just a prototype for vehicle controls. Spawns a vehicle when you join for the moment.
> New Vehicle Controls

- src/core/client/views/hud/html/components/chat.js
Added appendPrevious and addZero functions to chat component, timestamp output changed with added zeros.
> Chat - Previous Function and Add Zero For Timestamp

- src/core/server/extensions/playerFunctions/inventory.ts
Get an Array of all available inventory slots
> Added getFreeInventorySlots

- src/core/client/systems/marker.ts
- src/core/client/utility/marker.ts
- src/core/shared/interfaces/Marker.ts
added bobUpAndDown
added faceCamera
> Added more functions to Markercontroller

- src/core/server/systems/interior.ts
Fixed Typo - Caused a promise Error on Linux Server.
> Fixed Typo

- src/core/server/athena/main.ts
- src/core/server/commands/noclip.ts
- src/core/server/commands/setHealth.ts
Fixes the 101% Health issue probably
> Fix 101% health

- src-webviews/src/pages/chat/Chat.vue
This basically fixes command suggestions not hiding whenever we type "/" and then press ESC.
> Fix command suggestions not hiding

- src-webviews/src/App.vue
```html
<h1 id="page-[object Object]">HelloWorld</h1>
```
```html
<h1 id="page-HelloWorld">HelloWorld</h1>
```
> Fix Page Bindings

- src/core/plugins/core-interior/src/system.ts
Option to skip distance and owner checks for Interior methods (setPrice, setName, purchase) added. Needed for hotel and real estate management.
RemoveOwner Method added.
> Skip Distance and Ownership check, RemoveOwnership

- src/core/plugins/core-atm/src/view.ts
> ATM add configurable Interaction Range

- src/core/server-plugins/core-items/src/registerItems.ts
- Adding version string to weapons
> Update registerItems.ts 

- src/core/client/systems/interaction.ts
- src/core/server/athena/main.ts
- src/core/server/extensions/vehicleFuncs.ts
- src/core/shared/enums/vehicle.ts
`VEHICLE_DISPLAY_LOCK_STATUS` = The lock symbol above the vehicle (default: true)
`VEHICLE_DISPLAY_LOCK_INTERACTION_INFO` = The interaction info in the hud (default: true)
Just trying to make athena more configurable :)
> Added some config options

- src/core/server/systems/agenda.ts
This PR aims to:
- keep an evidence of the agenda order
- humanize log, so you can see exactly what and how
- facilitate the way we keep track of the order of agenda sequence
> Keep an Evidence of the Agenda Order

- src/core/server/extensions/playerFunctions/inventory.ts
I have made a fiew plugins like shop or farming in der_Lords opensource-stuff. Mostly we are adding items, sometimes good, sometimes bad. I was working on these codelines to have one "plugin-way" to add and remove amounts of items from or to inventory by looking at stacks and quantities. Though i dont want to add these methods to every plugin now, so it'll shall be in the core-funcs.
If some of the amount couldn't be added or removed the left-over-amount is returned.
TODO: Item-Weight.
> Inventory add/remove by quantity and stacking

- src/core/server/commands/item.ts
The german word for 'egg' is 'ei' so now we can get it ;)
> Enable getting Items with at least two letters

- src/core/plugins/core-items/server/src/items.ts
We are currently only having food items but no single drinkable item. This PR changes it by adding 2 drinkable Items
> Add some drinkable items

- .swcrc
- src/core/server/decorators/commands.ts
- src/core/shared/decorators/commands.ts
- src/tsconfig.json
Currently, we have lots of imports and registration stuff we have to handle. Decorations allow us to 'magically' do things which simplyfies some stuff.
This PR also comes with an command method decorator - see the example below.
```ts
class MyCommandGroup {
@command('reviveme', '/reviveme - Revives you.', PERMISSIONS.ADMIN)
static reviveMe(player: alt.Player) {
player.health = 200;
player.clearBloodDamage();
player.spawn(player.pos);
}
}
```
```ts
export function interaction(pos: IVector3, description: string, dim: number) {
return (_target: Function, _propertyName: string, descriptor: PropertyDescriptor) => {
const callback: (player: alt.Player, ...args: any[]) => void = descriptor.value;
Athena.controllers.interaction.add({
position: pos,
description: description,
dimension: dim, …
```
> Enable decorator support and add commands decorator

- src/core/plugins/core-commands/server/commands/console/index.ts
- src/core/plugins/core-commands/server/commands/consoleCommands.ts
- src/core/plugins/core-commands/server/index.ts
Sorry guys, here we go
Also fixed /dox command and removed old discord commands.
> Readd Terminal Commands, and small fixes to dox command.

- src/core/shared/configurations/shared.ts
FORCE_SCREEN_SHAKE is never used, instead SHOULD_SCREEN_SHAKE is used.
> Changed FORCE_SCREEN_SHAKE to SHOULD_SCREEN_SHAKE

- src/core/plugins/core-character-creator/webview/components/Info.vue
In info.vue on line 99 there was a typing error it said Maixmum instead of Maximum that has been solved with this pull request
> type error fixed in info.vue

- src/core/server/views/inventory.ts
see feature request https://github.com/Stuyk/altv-athena-issues/issues/35
> Handover player in Inventory rules

- src/core/server/extensions/vehicleFuncs.ts
Useful when you want to modify stuff BEFORE a vehicle is being created and saved into the database for the first time
> Add `BeforeAddVehicleInjections` Vehicle Injection

- src/core/client/systems/vehicle.ts
- src/core/plugins/core-commands/server/commands/player/seatbelt.ts
Fix notification of sealtbelt on/off
> Seatbelt Notifications

- src/core/client/systems/vehicle.ts
- src/core/plugins/core-commands/server/commands/player/seatbelt.ts
- src/core/plugins/core-hud/client/index.ts
- src/core/plugins/core-hud/webview/components/Speedo.vue
- src/core/shared/enums/hudComponents.ts
Replacing the "/" with an functional seatbelt icon
> Seatbelt Indicator

- src/core/plugins/core-factions/webview/pages/Bank.vue
- src/core/plugins/discord/server/index.ts
- src/core/plugins/discord/server/src/discordController.ts
Removed redunant awaits, added proper JSDOcs Annotations
> Discord Plugin, small refactoring

- src-webviews/src/pages/inventory/Inventory.vue
> Fix yellow arrow BUG

- package.json
Caused the server to not start on linux with npm run linux:cdn
> Removed double && in package.json

- src/core/server/systems/vehicle.ts
replaced no vehicle storage notification with LOCALE_KEYS.VEHICLE_NO_STORAGE.
> replaced no vehicle storage notification

- src/core/server/views/inventory.ts
- src/core/server/views/storage.ts
- src/core/shared/locale/languages/en.ts
- src/core/shared/locale/languages/keys.ts
If you added your own language file, you need to add the missing values to your language file. Look at the core/shared/locale/languages/en.ts language file for an example.
> added more locale keys for locale controller

- src/core/server/systems/admin.ts
- src/core/server/systems/blip.ts
- src/core/server/systems/interaction.ts
- src/core/server/systems/login.ts
- src/core/server/views/login.ts
- src/core/shared/locale/languages/en.ts
- src/core/shared/locale/languages/keys.ts
If you added your own language file, you need to add the missing values to your language file. Look at the core/shared/locale/languages/en.ts language file for an example.
> added more locale keys and updated locales

- src/core/server/extensions/vehicleFuncs.ts
- src/core/shared/locale/languages/en.ts
- src/core/shared/locale/languages/keys.ts
If you added your own language file, you need to add the missing values to your language file. Look at the core/shared/locale/languages/en.ts language file for an example.
> replaced vehicleFuncs texts with locale keys

- src/core/client/systems/interiors.ts
> Added ipl for missing house

- scripts/runtime/index.js
Need this if someone happens to have dependencies for Vue
> Update dependencies for all the things before any build or server start

- scripts/compiler/core.js
DAMNIT i need my MD to be copied
> Remove *.md from file path exclusion

- src/core/client/startup.ts
- src/core/client/utility/entitySets.ts
- src/core/plugins/core-interior/server/src/interiors.ts
- src/core/plugins/core-interior/server/src/system.ts
- src/core/plugins/core-interior/shared/interfaces.ts
- src/core/shared/enums/system.ts
- src/core/shared/interfaces/iEntitySet.ts
- Added support for EntitySets in general.
- Integrated EntitySets into the interior plugin. This includes adding the two existing Entitysets for the Diamond-Casino to the default interiors.
> Added support for Enitysets

- src/core/plugins/core-barbershop/server/src/view.ts
Original code - This treated player ID 0 and 1 as false / true in the if statement.
`        if (!sessions[hairDresserID]) {
if (sessions[hairDresserID] === undefined) {
return;
}`
Incoming change - This fixes the player ID check. Allowing ID 0 and 1 players to get their hair cut.
`            if (sessions[hairDresserID] === undefined) {
return;
}`
> fix - player id 0/1 being treated as true/false

- src/core/server/extensions/playerFunctions/safe.ts
Added safe way to subHealth and subArmour
Copied from addHealth and AddArmour and then adjusted the math
> added subHealth and subArmour safe functions

- src/core/plugins/core-commands/server/commands/moderator/vehicle.ts
Now the repair command gets the closest vehicle if the player istn't inside a vehicle and repairs it.
> modified repair command

- src/core/plugins/core-character-select/server/src/view.ts
- src/core/plugins/discord/server/src/discordController.ts
- src/core/server/systems/character.ts
Fix the error: User was not in discord.
> Fix Discord Bot

- src/core/server/systems/account.ts
> Resolves a critical issue which does not let you create accounts.

- src/core/server/extensions/playerFunctions/sync.ts
fix ternary conditional operator, which sets it to 0 when hours = 0
> playTime conditional fix to avoid always 0 value

- src/core/server/systems/job.ts
Rename attacheable to attachable.
> Fix job attachable related error

- src-webviews/src/pages/chat/Chat.vue
Preventing chat input unfocusing when pressing tab
> Preventing tab unfocus chat input

- AthenaConfig.json
- src/core/server/interface/iConfig.ts
- src/core/server/utility/mongo.ts
Set custom Database in AthenaConfig.json
> [Core/Database] Ability to set Database in Config

- README.md
- src/core/client/startup.ts
- src/core/client/utility/missionText.ts
- src/core/server/extensions/playerFunctions/emit.ts
- src/core/shared/enums/system.ts
missionText are useful subtitles on the bottom of the screen. It should reduce instructions for player on chat and notify
> Add missionText to Athena.player.emit

- src/core/server/extensions/playerFunctions/inventory.ts
The isItemIn function was for equipment, toolbar and not only for inventory.
> Fix function isItemIn for equipment search

- src/core/client/systems/athenaEvents.ts
> Replace AthenaEvents Static Class

- src/core/client/utility/raycast.ts
Can be used for better object interaction. Instead of camera view the players facing direction will be used.
> Raycast in the player's facing direction

- src/core/client/api/consts/utilityConst.ts
- src/core/client/utility/switch.ts
- src/core/plugins/core-character-select/client/src/view.ts
- src/core/shared/enums/switchOutTypes.ts
At first I though the code was trying to use `natives.switchInPlayer` but I realized there was an un-exposed controller for switch cam effect. So basically I exposed that method, added a parameter to choose the switch type and fixed the method in the view code.
> Fixed Character Selector switchInPlayer

- src/core/plugins/core-commands/server/commands/moderator/inventory.ts
- src/core/shared/locale/languages/en.ts
- src/core/shared/locale/languages/keys.ts
Related Issue: https://github.com/Stuyk/altv-athena/issues/296
> /getitem - Also get items by dbName

- src/core/plugins/core-inventory/server/src/view.ts
- src/core/plugins/core-inventory/webview/components/Grid.vue
- src/core/server/systems/inventory/effects.ts
- src/core/server/systems/inventory/manager.ts
- src/core/shared/interfaces/item.ts
Introduced the possibility to add custom context menu actions for items in inventory.
Also the "Use"-Action gets now only shown, if the item could actually be used.
> Added: Custom context menu actions for inventory

- src/core/client/streamers/object.ts
Didnt save/load object rotation properly.
> Fix Object Rotation Bug

- src/core/client/systems/character.ts
- src/core/client/views/input.ts
- src/core/server/events/playerConnect.ts
- src/core/server/player/setter.ts
- src/core/shared/interfaces/vehicleBase.ts
Most of them are clear. The only thing to discuss ist the point vehicleBase.group Optional or required. In add.ts the attribute is missing in ownedVehicle.  So I set it to optional for now.
> Some small fixes

- src/core/plugins/core-commands/server/commands/moderator/vehicle.ts
If seated in large vehicles, the commands would say 'no vehicle in range'
> fix commands not working always for large vehicles

- src/core/server/vehicle/controls.ts
please ignore the other 4 commits, I don't understand git enough to understand why they need to exist.
> fixed race condition for engine start/stop event

- src/core/client/camera/cinematic.ts
switchNode Function by @Booster1212 
previous Function by @MnkyArts
> Update Cinematic Camera. Previous/Index Function.

- scripts/compiler/core.js
Creates resources folder if not exists.
> Fix for first compilation after clone
