Stuyk/altv-athena

- src/core/server/commands/inventory.ts
- src/core/server/extensions/playerFunctions/sync.ts
- src/webview/client/inventory/app.js
Inventory has 5 tabs. But Array was 6. Players could have items in a 6th non visible tab.
> Remove nonexistent tab from inventory structure

- src/core/client/extensions/view2.ts
Maybe it's someone who doesn't want to hide all the overlays, and just wants to hide the chat, for example, or whatever.
Usage:
```ts
// hide the overlay
WebViewController.setOverlayVisible('Chat', false);
// show the overlay
WebViewController.setOverlayVisible('Chat', true);
```
> Add setOverlayVisible to WebViewController

- src/core/server/systems/item.ts
So you can't duplicate an item if you use an InputMenu to create a key in-game for Example.
> Pushing dbName Array after ItemFactory.add(<Item>)

- src-webviews/src/pages/multiPageExample/MultiPageExample.vue
So players don't have to import it in copied examples.
> AthenaComponents (MultiPageExample)

- src/core/plugins/core-fuel/server/src/fuel.ts
- src/core/server/extensions/vehicleFuncs.ts
- src/core/shared/interfaces/iVehicle.ts
Also removes the `updateVehicleMods` method since everything can be handled via plugins now. Also think it's not a good idea to keep it in core.
This also removes the `addCreateVehicleInjection` method since you can use the `ATHENA_EVENTS_VEHICLE.SPAWNED` for it.
> Add `BeforeSpawnInjection` and `BeforeDespawnInjection` hooks

- src/core/plugins/core-character-creator/webview/CharacterCreator.vue
Only useable on the first 4 pages so you can still move the camera while editing the character, game controls are blocked on last index, so you cannot move the character by typing into the inputs.
> Resolve Character Creator moving character while using input

- src/core/client/events/connectionComplete.ts
temporary disabled area name display in vehicle, because the text is under the hud and not really readable.
> temporary disabled area name display in vehicle

- src/core/client/systems/interiors.ts
This fixes the destroyed pillbox hill hospital which is imho a better default setting for a hospital in the middle of the city. But I think that's a matter of taste, it's just a suggestion.
Before:
After:
> Fixed destroyed pillbox hill hospital

- src/core/plugins/core-garage/server/src/view.ts
Allow custom spawned vehicles without "_id"s. Just an undefined-check to avoid exception.
> garage-fix

- src/core/server/systems/chat.ts
- src/core/server/systems/permission.ts
Adding the ability to have a Superadmin use every command with "lower" roles below him (inherited rights)
> Changeable permission-strategy for chat-commands

- src/core/client/events/keyHeld.ts
Helps https://github.com/Stuyk/altv-athena/pull/262#pullrequestreview-1079627523 to re-register keybinds - even tho you don't nessesarily need it because `KeyHeld.register` overwrites existing handlers anyway.
Also makes no sense to require both, keyDown and an keyUp callback because it's not always needed.
> Add `KeyHeld.unregister` method and make register and unregister callbacks optional

- src-webviews/src/css/button.css
This will remove Button `@click` triggers when Button has `:disable="true"` and other click animations if are
> Don't allow Button to use @ click events when disabled

- src/core/plugins/core-factions/server/src/commands.ts
- src/core/plugins/core-factions/server/src/handler.ts
- src/core/plugins/core-factions/shared/interfaces.ts
This code will add `type` as a parameter for /fcreate.
This will be needed for future systems ( like arrest systems, gangwar systems etc - to check what kind of faction it is without using the faction ID. )
> [Core-Factions] : Added Faction Type for better overview.

- src/core/server/streamers/item.ts
The player can currently pick up items from another dimension even if he cannot see them. The change ensures that the player only receives items from his current dimension.
> Restrict drops to players dimension

- src/core/client/menus/object.ts
- src/core/client/systems/interaction.ts
The GroundItem (if exists) of a selected object will be transfert to the ObjectWheelMenu as optional parameter. This allows you to add menu entries related to the item instead to the object. 
Just a small example use case: Place an "water dispenser" on the ground. In the "water dispenser"-Item is the water level saved. The ObjectWheelMenu gives you an Option to "Drink". But if the the dispenser is empty the option should be no longer available.
> Handsover Object's Item to WheelMenu Injections

- src/core/server/extensions/playerFunctions/safe.ts
Small edit to `Safe.setPosition` where it set the position of the vehicle if the player is in one and is driver instead of setting the player position only.
Tested and works in city and even on mountain.
> Set position of vehicle if player is driver

- src/core/plugins/core-hud/client/index.ts
- src/core/plugins/core-hud/webview/Hud.vue
- src/core/plugins/core-hud/webview/components/Speed.vue
- src/core/shared/configurations/shared.ts
- src/core/shared/enums/hudComponents.ts
If wanted a config entry allows the HUD-Speedometer to displays the speed in knots (KN) if you're in a boat or aircraft.
The process of determining the unit was moved from the webview itself to the client index file.
> speedo knots display

- src/core/plugins/core-commands/server/commands/moderator/door.ts
Fixed an error where the `/toggledoor` command would state the inverse state of the toggled door.
This happened because for the output the value of the `isLocked` variable was inverted after the variable was changed to toggle the lock.
Additionally, I added a check so only doors in a radius of 5 meters can be toggled. After some testing, this seems like an overly excessive distance, but I left it at 5. This distance should be set by the server admin to their liking.
> Fix door controller command

- src/core/plugins/core-commands/server/commands/moderator/door.ts
- src/core/plugins/core-commands/server/commands/moderator/skins.ts
In the command, there is the option to change the skin of another player. However, the old code would always change the skin of the command-executing player, not the targeted one.
> Fixed wrong targeting

- src/core/server/utility/closest.ts
If the player had the id 0, the find-Method returned 0 and therefore the player passed the filter accidentially.
> Fixed: Closest player returned own player

- src/core/client/systems/noclip.ts
Before when having noclip on, mouse movement would rotate the camera, even when in the pause menu.
I added an if-statement that checks before wether the menu is open before executing the camera rotation.
> Fix camera moving in pause menu while noclipping

- src/core/plugins/core-commands/server/commands/moderator/skins.ts
- src/core/plugins/core-commands/server/commands/moderator/test.ts
- src/core/plugins/core-commands/server/commands/moderator/vehicle.ts
- src/core/server/vehicle/tuning.ts
List of commands updated to v5:
- /testerrorscreen
- /testworldhelptext
- /testspinner
- /testshard
- /testcredits
- /testobjectattach
- /testobjectattachinfinite
- /testjobmenu
- /testped
- /testactionmenu
- /fullTuneVehicle
- /sessionvehicle
- /setVehicleLivery & /svl
- /setvehicledirtLevel & /svdl
Also updated the vehicleRepair command to update the lastUsed value, all vehicle-creation commands to tell the user if no model was specified and the clearSkin command to tell the user the name of the removed skin.
Currently the vehicleHandling and neonLight commands are not updated. This is due to the needed systems not being in place yet.
> updated several commands to v5

- src/core/server/controllers/staticPed.ts
The ``animation`` argument was typed as an array. If it was intended to be an array, it is not handled correctly on the client-side, so animations for static ped simply did not work.
> Fixed argument in playAnimation for static peds

- src/core/client/menus/vehicle.ts
Before: When standing outside of a vehicle and opening the vehicle wheel menu, nothing did happen on lock/unlock menu action.
Reason: The emit to the server didn't send the vehicle property with it, so the server just checked for the vehicle a player is sitting in.
After: The emit includes the selected vehicle entity and the lock/unlock menu action works properly.
> Fixed: Vehicle menu not locking/unlocking

- src/core/client/webview/index.ts
When the player local meta is not initialized, a page is created and the page is opened to report an error: Cannot read properties of undefined (reading 'isDead')
> Fix error when meta is uninitialized

- src/core/client/rmlui/menu3d/index.ts
Previously after selecting an option that's not the first one, creating new menu and clicking arrow up or down, two options would be selected. Resetting the index fixes that.
> Reset optionIndex when initiating a menu3d

- src/core/server/vehicle/tuning.ts
Otherwise getTuning/getMods will always return 0 as value for id 23/24 (front/rearwheels) since vehicle.getMods(id); cant read it properly. 
Usefull for buy functionality.
> Wheel Tuning Adaption
